authors:
  zeul:
    name: Zeul Mordasiewicz
    description: zeul
    avatar: https://avatars.githubusercontent.com/u/55005377
    url: https://github.com/zeulewan
  anthony:
    name: Anthony Dalgliesh
    description: anthony
    avatar: https://avatars.githubusercontent.com/u/111382170?v=4&size=64
    url: https://github.com/anthonydalgliesh
